pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker { image 'maven' }
            }
            steps {
                dir ('backend') {
                    sh "mvn package -Dmaven.test.skip=true"
                }
            }
        }
    }
}